[".oh-my-zsh/custom/themes/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k.git"

[".oh-my-zsh/custom/plugins/base16-shell"]
type = "git-repo"
url = "https://github.com/chriskempson/base16-shell.git"
