# This setting specifies the user that MPD will run as. MPD should never run as
# root and you may use this setting to make MPD change its user ID after
# initialization. This setting is disabled by default and MPD is run as the
# current user.
#
# Inutile ici car le service est lance avec le user tony (systemctl --user)
# user "tony"

music_directory		"~/Music"
playlist_directory "~/.config/mpd/playlists"
db_file "~/.config/mpd/mpd.db"
log_file "~/.config/mpd/mpd.log"
pid_file "~/.config/mpd/mpd.pid"
state_file "~/.config/mpd/mpdstate"

bind_to_address		"127.0.0.1"
port				"6600"

#audio_output {
# type		"alsa"
# name		"ALSA Device"
# device		"hw:1,0"
## options	"dev=dmixer"
# mixer_type     "software" 
#}

audio_output {
        type            "pulse"
        name            "pulse audio"
}
