#! /bin/sh

bspc config border_width		2
bspc config window_gap			24 

bspc config split_ratio			0.5
bspc config borderless_monocle		true
bspc config gapless_monocle		true

# Interact with mouse pointer + mod1 = alt
bspc config pointer_modifier		mod1
bspc config focus_follows_pointer	true

bspc config focused_border_color 	"#6666EA"
bspc config presel_feedback_color 	"#6666EA"

bspc monitor -d TERM WEB MAIL DEV OFFICE CHAT MEDIA GAMES DOWNLOADS PASSWORDS

bspc rule -a feh state=floating center=on 
bspc rule -a URxvt:ncmpcpp state=floating
bspc rule -a Pinentry:pinentry state=floating
bspc rule -a Firefox desktop=WEB follow=on
bspc rule -a Thunderbird desktop=MAIL follow=on
bspc rule -a Thunderbird:Msgcompose state=floating
bspc rule -a URxvt:ranger desktop=OFFICE follow=on
bspc rule -a Zathura desktop=OFFICE follow=on
bspc rule -a mpv desktop=MEDIA state=fullscreen follow=on
bspc rule -a KeePass2 desktop=PASSWORDS follow=on

$HOME/.config/bspwm/panel/panel &
