#! /bin/sh

bspc config border_width        2
bspc config window_gap        	24 

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config focused_border_color "#6666EA"
bspc config presel_feedback_color "#6666EA"

bspc monitor -d TERM WEB MAIL DEV OFFICE CHAT MEDIA GAMES DOWNLOADS PASSWORDS

bspc rule -a Firefox desktop=WEB follow=true
bspc rule -a mpv desktop=MEDIA follow=true
bspc rule -a Thunderbird desktop=MAIL follow=true
bspc rule -a KeePass2 desktop=PASSWORDS follow=true

$HOME/.config/bspwm/panel/panel &
